/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val nombre: String = "cruza"
    var edad = 16
    println("hola $nombre")
    println("Tengo ${edad + 1} años el próximo año")
}